services:
  app:
    build: .
    container_name: pezesha-lms-app
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/pezesha_lms
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
    depends_on:
      - db
    networks:
      - lms-network

  db:
    image: postgres:16-alpine
    container_name: pezesha-lms-db
    environment:
      - POSTGRES_DB=pezesha_lms
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lms-network

volumes:
  postgres_data:

networks:
  lms-network: